services:
  memos-rss:
    image: ghcr.io/imnyang/memos-rss/bot:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/usr/app/data
      - ./rss.toml:/usr/app/rss.toml
      - /etc/localtime:/etc/localtime:ro
