services:
  memos-rss:
    image: ghcr.io/imnyang/memos-rss/bot:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./processed_items.db:/usr/app/processed_items.db
#      - ./processed.json:/app/processed.json # if you need to migration
      - ./rss.toml:/usr/app/rss.toml
