[geeknews]
channel = "1448338163864174867"
tag = "1448338238963056691"
emoji = "ðŸ¤“"
rss = "https://feeds.feedburner.com/geeknews-feed"

[svrforum]
channel = "1448338163864174867"
tag = "1448338289147908108"
emoji = "ðŸ’»"
rss = "https://svrforum.com/rss"
category_filter = ["ìœ ë¨¸&ì •ë³´"]